### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by hasezoey** [HarelAshwal/typegoose-frontend#1]
(from http://github.com/szokodiakos/typegoose/pull/96 )
- why is this needed? / why typegoose on the frontend
- could i have an example (use case)?

**Comment by HarelAshwal** [comment]
LK"I

Currently you need to declare the model in two places, in server side, and in client side.
the client side (for instance Angular compiler) can't use the server side model, because it has reference to server-only packages (e.g. mongoose).

The changes in this repo let you use the EXACT same model for both the client and the server.
(it detects if running on browser it will just ignore all typegoose specific code).

**Comment by hasezoey** [comment]
i mean like, why is the model needed at all in the frontend, not just an interface?

**Comment by HarelAshwal** [comment]
you don't need it.
it just a convenient way to write code without duplicating the code (and write the interface for the model in client side).
